### ISSUE TITLE
CodeStar Integration Example

### ISSUE THREAD

**Issue by cknuteson-firstlook** [sbstjn/cra-serverless#1]
Hey,

Thanks for this GREAT example app! 

I was curious to know if it would make sense to use the CDK scaffold/build commands within a project generated by CodeStar. The centralized view of the application CS offers is appealing, but I'm concerned that the CDK may not play well with the stack (IAM permissions relative to what the CDK needs/visibility of the CDK generated components/etc).

Any feedback/thoughts are welcome, thanks again!

**Comment by sbstjn** [comment]
I like the idea!

In general, I try to avoid using the CDK for deployments inside CodeBuild. Therefore I did use the `CodePipelineAction` to deploy raw CloudFormation stacks (created with the cdk of course) instead of using the CDK inside CodeBuild.

But you can use the CDK to create all needed files to deploy the example using CodeStar etc.

If I do understand the [CodeStar API docs](https://docs.aws.amazon.com/cli/latest/reference/codestar/create-project.html) correctly, you can provide a GitHub repository as the source for a project in CodeStar, but the `toolchain` configuration must be stored in an S3 Bucket. Basically, it's not possible to create a project like 

```
# Not Working, Pseudo-syntax
$ > aws codestar create-project --from https://github.com/sbstjn/cra-serverless
```

But, it seems to be doable to extend the existing tooling and use CS as an alternative to the `yarn cdk deploy cra-serverless-pipeline` command. This requires more complex tooling to configure the basics:

- Keep using CDK to create CloudFormation Stacks
- Use CDK to create `toolchain.yml` for CodeStar
- Use CDK to deploy CloudFromation Stack with an S3 Bucket for `toolchain.yml` file
- Upload `toolchain.yml` file to S3 for CodeStar usage
- Use AWS CLI to create a CodeStar project
  - the local/cloned repository as a source
  - the uploaded `toolchain.yml` from S3

Not that complex, but I'm not sure if it's worth the effort. 🤔

**Comment by cknuteson-firstlook** [comment]
Thanks for the quick response. After some poking, here's what I was able to get sort-of working:
* Start with CodeStar to create the repo/toolchain
* Port over repo
* Add IAM permissions to role created by CodeStar
*  Run `yarn cdk deploy cra-serverless-pipeline` in _Build_ stage
* Success(?)

I'm with you in thinking it's not worth the effort to shoehorn the CDK into CodeStar...  seems like it'd just be adding an unnecessary layer to the deploy pipeline. Appreciate the effort in this!
